/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed-variant": "#464747",
        "secondary-container": "#fed488",
        "surface-container-lowest": "#ffffff",
        "tertiary-container": "#1b1c1c",
        "surface-container-low": "#f5f3ef",
        "on-surface": "#1b1c1a",
        "outline-variant": "#c4c7c7",
        "secondary-fixed": "#ffdea5",
        "primary-fixed": "#e5e2e1",
        "on-surface-variant": "#444748",
        "error-container": "#ffdad6",
        "tertiary": "#000000",
        "surface-container-highest": "#e4e2de",
        "on-primary-container": "#858383",
        "primary-container": "#1c1b1b",
        "background": "#fbf9f5",
        "tertiary-fixed": "#e4e2e2",
        "on-primary-fixed": "#1c1b1b",
        "error": "#ba1a1a",
        "surface-container": "#efeeea",
        "on-primary-fixed-variant": "#474746",
        "on-tertiary-container": "#848484",
        "on-secondary-container": "#785a1a",
        "tertiary-fixed-dim": "#c7c6c6",
        "surface-container-high": "#eae8e4",
        "on-tertiary": "#ffffff",
        "surface-tint": "#5f5e5e",
        "secondary-fixed-dim": "#e9c176",
        "secondary": "#775a19",
        "on-secondary-fixed": "#261900",
        "on-tertiary-fixed": "#1b1c1c",
        "surface-bright": "#fbf9f5",
        "on-error-container": "#93000a",
        "on-error": "#ffffff",
        "on-background": "#1b1c1a",
        "primary": "#000000",
        "on-secondary-fixed-variant": "#5d4201",
        "on-primary": "#ffffff",
        "inverse-on-surface": "#f2f0ed",
        "surface-dim": "#dbdad6",
        "surface-variant": "#e4e2de",
        "inverse-surface": "#30312e",
        "primary-fixed-dim": "#c8c6c5",
        "surface": "#fbf9f5",
        "on-secondary": "#ffffff",
        "inverse-primary": "#c8c6c5",
        "outline": "#747878"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "margin-page": "4rem",
        "margin-mobile": "1.5rem",
        "stack-md": "2rem",
        "stack-lg": "4rem",
        "reading-column-max": "720px",
        "stack-sm": "1rem",
        "gutter": "2rem"
      },
      fontFamily: {
        "body-lg": ["Libre Caslon Text", "serif"],
        "display-lg-mobile": ["Playfair Display", "serif"],
        "headline-sm": ["Playfair Display", "serif"],
        "body-md": ["Libre Caslon Text", "serif"],
        "ui-label": ["Inter", "sans-serif"],
        "ui-small": ["Inter", "sans-serif"],
        "display-lg": ["Playfair Display", "serif"],
        "headline-md": ["Playfair Display", "serif"]
      },
    },
  },
  plugins: [],
}
